{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-10-07 20:14:28,818\tWARNING deprecation.py:50 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import django\n",
    "import os\n",
    "file_dir = \"/Users/mirbilal/Desktop/MobCommission/commissionV2/\"\n",
    "if file_dir not in sys.path:\n",
    "    sys.path.insert(0, file_dir)\n",
    "\n",
    "os.environ[\"DJANGO_SETTINGS_MODULE\"] = \"commissionerv2.settings\"\n",
    "os.environ[\"DJANGO_ALLOW_ASYNC_UNSAFE\"] = \"true\" \n",
    "django.setup()\n",
    "import numpy as np\n",
    "import json\n",
    "from datetime import datetime\n",
    "from dateutil.relativedelta import relativedelta\n",
    "import pytz\n",
    "import pandas as pd\n",
    "import cufflinks as cf\n",
    "from django.db.models import Q\n",
    "from apps.environment_simulator.sevice_layer.market_simulator import MarketSimulator\n",
    "from apps.environment_simulator.models import SimulatedStockBuffer\n",
    "import gymnasium as gym\n",
    "import ray\n",
    "from gymnasium import spaces\n",
    "from ray.rllib.algorithms import ppo\n",
    "from os import path, environ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-10-07 20:14:32,568\tINFO worker.py:1642 -- Started a local Ray instance.\n",
      "2023-10-07 20:14:32,936\tINFO packaging.py:518 -- Creating a file package for local directory '/Users/mirbilal/Desktop/MobCommission/commissionV2/'.\n",
      "2023-10-07 20:14:33,190\tINFO packaging.py:346 -- Pushing file package 'gcs://_ray_pkg_31ebffced6f562bb.zip' (6.55MiB) to Ray cluster...\n",
      "2023-10-07 20:14:33,221\tINFO packaging.py:359 -- Successfully pushed file package 'gcs://_ray_pkg_31ebffced6f562bb.zip'.\n",
      "2023-10-07 20:14:35,647\tWARNING algorithm_config.py:2578 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.\n",
      "2023-10-07 20:14:35,648\tWARNING algorithm_config.py:672 -- Cannot create PPOConfig from given `config_dict`! Property models not supported.\n",
      "/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:484: RayDeprecationWarning:\n",
      "\n",
      "This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "`UnifiedLogger` will be removed in Ray 2.7.\n",
      "\n",
      "/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning:\n",
      "\n",
      "This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "\n",
      "/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning:\n",
      "\n",
      "This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "\n",
      "/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning:\n",
      "\n",
      "This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=16146)\u001b[0m DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!\n",
      "2023-10-07 20:14:45,812\tERROR actor_manager.py:500 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16143, ip=127.0.0.1, actor_id=5bb16175e3665998fa32ac3901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1b5f71fc0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "    class SimulatedCommodity(models.Model):\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "    app_config = apps.get_containing_app_config(module)\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "    self.check_apps_ready()\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
      "2023-10-07 20:14:45,814\tERROR actor_manager.py:500 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16144, ip=127.0.0.1, actor_id=49cb93b5edec8a316609d08201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1bb3d6020>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "    class SimulatedCommodity(models.Model):\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "    app_config = apps.get_containing_app_config(module)\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "    self.check_apps_ready()\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
      "2023-10-07 20:14:45,814\tERROR actor_manager.py:500 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16145, ip=127.0.0.1, actor_id=dbb3fed9c984525607df1cb101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1b7cedfc0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "    class SimulatedCommodity(models.Model):\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "    app_config = apps.get_containing_app_config(module)\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "    self.check_apps_ready()\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
      "2023-10-07 20:14:45,815\tERROR actor_manager.py:500 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16146, ip=127.0.0.1, actor_id=3b6733c694966bf308ea5dc001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1b09f9ff0>)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "    class SimulatedCommodity(models.Model):\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "    app_config = apps.get_containing_app_config(module)\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "    self.check_apps_ready()\n",
      "  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m Apps aren't loaded yet.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 404, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 270, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 225, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 215, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     class SimulatedCommodity(models.Model):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     app_config = apps.get_containing_app_config(module)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     self.check_apps_ready()\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16146, ip=127.0.0.1, actor_id=3b6733c694966bf308ea5dc001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1b09f9ff0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   At least one of the input arguments for this task could not be computed:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m ray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     class SimulatedCommodity(models.Model):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     app_config = apps.get_containing_app_config(module)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     self.check_apps_ready()\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m   File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m     raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16146)\u001b[0m django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n"
     ]
    },
    {
     "ename": "RaySystemError",
     "evalue": "System error: Apps aren't loaded yet.\ntraceback: Traceback (most recent call last):\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 404, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 270, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 225, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 215, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n    class SimulatedCommodity(models.Model):\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n    app_config = apps.get_containing_app_config(module)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n    self.check_apps_ready()\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\ndjango.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayActorError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:157\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[0;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup)\u001b[0m\n\u001b[1;32m    156\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 157\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_setup(\n\u001b[1;32m    158\u001b[0m         validate_env\u001b[39m=\u001b[39;49mvalidate_env,\n\u001b[1;32m    159\u001b[0m         config\u001b[39m=\u001b[39;49mconfig,\n\u001b[1;32m    160\u001b[0m         num_workers\u001b[39m=\u001b[39;49mnum_workers,\n\u001b[1;32m    161\u001b[0m         local_worker\u001b[39m=\u001b[39;49mlocal_worker,\n\u001b[1;32m    162\u001b[0m     )\n\u001b[1;32m    163\u001b[0m \u001b[39m# WorkerSet creation possibly fails, if some (remote) workers cannot\u001b[39;00m\n\u001b[1;32m    164\u001b[0m \u001b[39m# be initialized properly (due to some errors in the RolloutWorker's\u001b[39;00m\n\u001b[1;32m    165\u001b[0m \u001b[39m# constructor).\u001b[39;00m\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:227\u001b[0m, in \u001b[0;36mWorkerSet._setup\u001b[0;34m(self, validate_env, config, num_workers, local_worker)\u001b[0m\n\u001b[1;32m    226\u001b[0m \u001b[39m# Create a number of @ray.remote workers.\u001b[39;00m\n\u001b[0;32m--> 227\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49madd_workers(\n\u001b[1;32m    228\u001b[0m     num_workers,\n\u001b[1;32m    229\u001b[0m     validate\u001b[39m=\u001b[39;49mconfig\u001b[39m.\u001b[39;49mvalidate_workers_after_construction,\n\u001b[1;32m    230\u001b[0m )\n\u001b[1;32m    232\u001b[0m \u001b[39m# If num_workers > 0 and we don't have an env on the local worker,\u001b[39;00m\n\u001b[1;32m    233\u001b[0m \u001b[39m# get the observation- and action spaces for each policy from\u001b[39;00m\n\u001b[1;32m    234\u001b[0m \u001b[39m# the first remote worker (which does have an env).\u001b[39;00m\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:593\u001b[0m, in \u001b[0;36mWorkerSet.add_workers\u001b[0;34m(self, num_workers, validate)\u001b[0m\n\u001b[1;32m    592\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m result\u001b[39m.\u001b[39mok:\n\u001b[0;32m--> 593\u001b[0m     \u001b[39mraise\u001b[39;00m result\u001b[39m.\u001b[39mget()\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py:481\u001b[0m, in \u001b[0;36mFaultTolerantActorManager.__fetch_result\u001b[0;34m(self, remote_actor_ids, remote_calls, tags, timeout_seconds, return_obj_refs, mark_healthy)\u001b[0m\n\u001b[1;32m    480\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 481\u001b[0m     result \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(r)\n\u001b[1;32m    482\u001b[0m     remote_results\u001b[39m.\u001b[39madd_result(actor_id, ResultOrError(result\u001b[39m=\u001b[39mresult), tag)\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:24\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     23\u001b[0m auto_init_ray()\n\u001b[0;32m---> 24\u001b[0m \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    102\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m--> 103\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/worker.py:2549\u001b[0m, in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   2548\u001b[0m         \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> 2549\u001b[0m             \u001b[39mraise\u001b[39;00m value\n\u001b[1;32m   2551\u001b[0m \u001b[39mif\u001b[39;00m is_individual_id:\n",
      "\u001b[0;31mRayActorError\u001b[0m: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16143, ip=127.0.0.1, actor_id=5bb16175e3665998fa32ac3901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1b5f71fc0>)\n  At least one of the input arguments for this task could not be computed:\nray.exceptions.RaySystemError: System error: Apps aren't loaded yet.\ntraceback: Traceback (most recent call last):\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n    class SimulatedCommodity(models.Model):\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n    app_config = apps.get_containing_app_config(module)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n    self.check_apps_ready()\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\ndjango.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mRaySystemError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m/Users/mirbilal/Desktop/MobCommission/commissionV2/scripts/environment_simulator/market_simulation.ipynb Cell 2\u001b[0m line \u001b[0;36m2\n\u001b[1;32m     <a href='vscode-notebook-cell:/Users/mirbilal/Desktop/MobCommission/commissionV2/scripts/environment_simulator/market_simulation.ipynb#W1sZmlsZQ%3D%3D?line=17'>18</a>\u001b[0m ray\u001b[39m.\u001b[39mshutdown()\n\u001b[1;32m     <a href='vscode-notebook-cell:/Users/mirbilal/Desktop/MobCommission/commissionV2/scripts/environment_simulator/market_simulation.ipynb#W1sZmlsZQ%3D%3D?line=18'>19</a>\u001b[0m ray\u001b[39m.\u001b[39minit(runtime_env\u001b[39m=\u001b[39m{\u001b[39m\"\u001b[39m\u001b[39mworking_dir\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m\"\u001b[39m\u001b[39m/Users/mirbilal/Desktop/MobCommission/commissionV2/\u001b[39m\u001b[39m\"\u001b[39m})\n\u001b[0;32m---> <a href='vscode-notebook-cell:/Users/mirbilal/Desktop/MobCommission/commissionV2/scripts/environment_simulator/market_simulation.ipynb#W1sZmlsZQ%3D%3D?line=19'>20</a>\u001b[0m algo \u001b[39m=\u001b[39m ppo\u001b[39m.\u001b[39;49mPPO(config\u001b[39m=\u001b[39;49mconfig)\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:517\u001b[0m, in \u001b[0;36mAlgorithm.__init__\u001b[0;34m(self, config, env, logger_creator, **kwargs)\u001b[0m\n\u001b[1;32m    499\u001b[0m \u001b[39m# Initialize common evaluation_metrics to nan, before they become\u001b[39;00m\n\u001b[1;32m    500\u001b[0m \u001b[39m# available. We want to make sure the metrics are always present\u001b[39;00m\n\u001b[1;32m    501\u001b[0m \u001b[39m# (although their values may be nan), so that Tune does not complain\u001b[39;00m\n\u001b[1;32m    502\u001b[0m \u001b[39m# when we use these as stopping criteria.\u001b[39;00m\n\u001b[1;32m    503\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mevaluation_metrics \u001b[39m=\u001b[39m {\n\u001b[1;32m    504\u001b[0m     \u001b[39m# TODO: Don't dump sampler results into top-level.\u001b[39;00m\n\u001b[1;32m    505\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mevaluation\u001b[39m\u001b[39m\"\u001b[39m: {\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    514\u001b[0m     },\n\u001b[1;32m    515\u001b[0m }\n\u001b[0;32m--> 517\u001b[0m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49m\u001b[39m__init__\u001b[39;49m(\n\u001b[1;32m    518\u001b[0m     config\u001b[39m=\u001b[39;49mconfig,\n\u001b[1;32m    519\u001b[0m     logger_creator\u001b[39m=\u001b[39;49mlogger_creator,\n\u001b[1;32m    520\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[1;32m    521\u001b[0m )\n\u001b[1;32m    523\u001b[0m \u001b[39m# Check, whether `training_iteration` is still a tune.Trainable property\u001b[39;00m\n\u001b[1;32m    524\u001b[0m \u001b[39m# and has not been overridden by the user in the attempt to implement the\u001b[39;00m\n\u001b[1;32m    525\u001b[0m \u001b[39m# algos logic (this should be done now inside `training_step`).\u001b[39;00m\n\u001b[1;32m    526\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/tune/trainable/trainable.py:185\u001b[0m, in \u001b[0;36mTrainable.__init__\u001b[0;34m(self, config, logger_creator, remote_checkpoint_dir, sync_config, storage)\u001b[0m\n\u001b[1;32m    182\u001b[0m     \u001b[39massert\u001b[39;00m storage\u001b[39m.\u001b[39mtrial_fs_path\n\u001b[1;32m    183\u001b[0m     logger\u001b[39m.\u001b[39mdebug(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mStorageContext on the TRAINABLE:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mstorage\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 185\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msetup(copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig))\n\u001b[1;32m    186\u001b[0m setup_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime() \u001b[39m-\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_start_time\n\u001b[1;32m    187\u001b[0m \u001b[39mif\u001b[39;00m setup_time \u001b[39m>\u001b[39m SETUP_TIME_THRESHOLD:\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:639\u001b[0m, in \u001b[0;36mAlgorithm.setup\u001b[0;34m(self, config)\u001b[0m\n\u001b[1;32m    636\u001b[0m \u001b[39m# Only if user did not override `_init()`:\u001b[39;00m\n\u001b[1;32m    637\u001b[0m \u001b[39mif\u001b[39;00m _init \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m:\n\u001b[1;32m    638\u001b[0m     \u001b[39m# Create a set of env runner actors via a WorkerSet.\u001b[39;00m\n\u001b[0;32m--> 639\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mworkers \u001b[39m=\u001b[39m WorkerSet(\n\u001b[1;32m    640\u001b[0m         env_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49menv_creator,\n\u001b[1;32m    641\u001b[0m         validate_env\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mvalidate_env,\n\u001b[1;32m    642\u001b[0m         default_policy_class\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_default_policy_class(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig),\n\u001b[1;32m    643\u001b[0m         config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig,\n\u001b[1;32m    644\u001b[0m         num_workers\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig\u001b[39m.\u001b[39;49mnum_rollout_workers,\n\u001b[1;32m    645\u001b[0m         local_worker\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    646\u001b[0m         logdir\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogdir,\n\u001b[1;32m    647\u001b[0m     )\n\u001b[1;32m    649\u001b[0m     \u001b[39m# TODO (avnishn): Remove the execution plan API by q1 2023\u001b[39;00m\n\u001b[1;32m    650\u001b[0m     \u001b[39m# Function defining one single training iteration's behavior.\u001b[39;00m\n\u001b[1;32m    651\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconfig\u001b[39m.\u001b[39m_disable_execution_plan_api:\n\u001b[1;32m    652\u001b[0m         \u001b[39m# Ensure remote workers are initially in sync with the local worker.\u001b[39;00m\n",
      "File \u001b[0;32m~/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py:179\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[0;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup)\u001b[0m\n\u001b[1;32m    166\u001b[0m \u001b[39mexcept\u001b[39;00m RayActorError \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    167\u001b[0m     \u001b[39m# In case of an actor (remote worker) init failure, the remote worker\u001b[39;00m\n\u001b[1;32m    168\u001b[0m     \u001b[39m# may still exist and will be accessible, however, e.g. calling\u001b[39;00m\n\u001b[1;32m    169\u001b[0m     \u001b[39m# its `sample.remote()` would result in strange \"property not found\"\u001b[39;00m\n\u001b[1;32m    170\u001b[0m     \u001b[39m# errors.\u001b[39;00m\n\u001b[1;32m    171\u001b[0m     \u001b[39mif\u001b[39;00m e\u001b[39m.\u001b[39mactor_init_failed:\n\u001b[1;32m    172\u001b[0m         \u001b[39m# Raise the original error here that the RolloutWorker raised\u001b[39;00m\n\u001b[1;32m    173\u001b[0m         \u001b[39m# during its construction process. This is to enforce transparency\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    177\u001b[0m         \u001b[39m# - e.args[0].args[2]: The original Exception (e.g. a ValueError due\u001b[39;00m\n\u001b[1;32m    178\u001b[0m         \u001b[39m# to a config mismatch) thrown inside the actor.\u001b[39;00m\n\u001b[0;32m--> 179\u001b[0m         \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39margs[\u001b[39m0\u001b[39m]\u001b[39m.\u001b[39margs[\u001b[39m2\u001b[39m]\n\u001b[1;32m    180\u001b[0m     \u001b[39m# In any other case, raise the RayActorError as-is.\u001b[39;00m\n\u001b[1;32m    181\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    182\u001b[0m         \u001b[39mraise\u001b[39;00m e\n",
      "\u001b[0;31mRaySystemError\u001b[0m: System error: Apps aren't loaded yet.\ntraceback: Traceback (most recent call last):\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 404, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 270, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 225, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/ray/_private/serialization.py\", line 215, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/__init__.py\", line 1, in <module>\n    from .simulated_commodity import SimulatedCommodity, SimulatedCommodityCovariance, SimulatedCommodityBuffer\n  File \"/tmp/ray/session_2023-10-07_20-14-30_347971_16109/runtime_resources/working_dir_files/_ray_pkg_31ebffced6f562bb/apps/environment_simulator/models/simulated_commodity.py\", line 4, in <module>\n    class SimulatedCommodity(models.Model):\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/db/models/base.py\", line 129, in __new__\n    app_config = apps.get_containing_app_config(module)\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 260, in get_containing_app_config\n    self.check_apps_ready()\n  File \"/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/django/apps/registry.py\", line 138, in check_apps_ready\n    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")\ndjango.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "db_params = {\n",
    "    'database': environ.get(\"POSTGRES_DB\"),\n",
    "    'user': environ.get(\"POSTGRES_USER\"),\n",
    "    'password': environ.get(\"POSTGRES_PASSWORD\"),\n",
    "    'host': environ.get(\"DB_HOST\"),\n",
    "    'port': environ.get(\"DB_PORT\"),\n",
    "}\n",
    "\n",
    "config = {\n",
    "        \"env\": MarketSimulator,\n",
    "        \"env_config\": {\"db_params\": db_params},\n",
    "        \"num_workers\": 4,\n",
    "}\n",
    "\n",
    "ray.shutdown()\n",
    "ray.init(runtime_env={\"working_dir\": \"/Users/mirbilal/Desktop/MobCommission/commissionV2/\"})\n",
    "algo = ppo.PPO(config=config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "ray.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "episode reward mean: 0 -0.991\n",
      "episode reward mean: 1 -0.991\n",
      "episode reward mean: 2 -0.991\n",
      "episode reward mean: 3 -0.9845\n",
      "episode reward mean: 4 -0.975\n",
      "episode reward mean: 5 -0.969\n",
      "episode reward mean: 6 -0.9535\n",
      "episode reward mean: 7 -0.941\n",
      "episode reward mean: 8 -0.925\n",
      "episode reward mean: 9 -0.9155\n",
      "episode reward mean: 10 -0.8895\n",
      "episode reward mean: 11 -0.871\n",
      "episode reward mean: 12 -0.8525\n",
      "episode reward mean: 13 -0.839\n",
      "episode reward mean: 14 -0.83\n",
      "episode reward mean: 15 -0.7985\n",
      "episode reward mean: 16 -0.7765\n",
      "episode reward mean: 17 -0.763\n",
      "episode reward mean: 18 -0.732\n",
      "episode reward mean: 19 -0.6855\n",
      "episode reward mean: 20 -0.6535\n",
      "episode reward mean: 21 -0.612\n",
      "episode reward mean: 22 -0.5745\n",
      "episode reward mean: 23 -0.5165\n",
      "episode reward mean: 24 -0.466\n",
      "episode reward mean: 25 -0.4075\n",
      "episode reward mean: 26 -0.314\n",
      "episode reward mean: 27 -0.205\n",
      "episode reward mean: 28 -0.0895\n",
      "episode reward mean: 29 0.002\n",
      "episode reward mean: 30 0.0945\n",
      "episode reward mean: 31 0.2065\n",
      "episode reward mean: 32 0.3075\n",
      "episode reward mean: 33 0.403\n",
      "episode reward mean: 34 0.538\n",
      "episode reward mean: 35 0.6285\n",
      "episode reward mean: 36 0.6785\n",
      "episode reward mean: 37 0.7575\n",
      "episode reward mean: 38 0.8075\n",
      "episode reward mean: 39 0.819\n",
      "episode reward mean: 40 0.869\n",
      "episode reward mean: 41 0.881\n",
      "episode reward mean: 42 0.9275\n",
      "episode reward mean: 43 0.95\n",
      "episode reward mean: 44 0.9515\n",
      "episode reward mean: 45 0.975\n",
      "episode reward mean: 46 0.9775\n",
      "episode reward mean: 47 0.9865\n",
      "episode reward mean: 48 0.9915\n",
      "episode reward mean: 49 0.989\n"
     ]
    }
   ],
   "source": [
    "mean_ppo = []\n",
    "for _ in range(50):\n",
    "\n",
    "    result = algo.train()\n",
    "    print(\"episode reward mean:\", _, result['episode_reward_mean'])\n",
    "    mean_ppo.append(result['episode_reward_mean'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1. 1. 2. 0. 1.]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/mirbilal/Desktop/MobCommission/commissionV2/v2env/lib/python3.10/site-packages/gymnasium/spaces/box.py:130: UserWarning:\n",
      "\n",
      "\u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "\n"
     ]
    }
   ],
   "source": [
    "MyEnv()\n",
    "obs = MyEnv()\n",
    "obs.reset()\n",
    "\n",
    "latest_action = algo.compute_single_action(0)\n",
    "print(latest_action)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tuple(Box(0.0, inf, (5, 8), float32), Box(0.0, inf, (6, 1), float32), Box(0.0, inf, (1,), float32))\n"
     ]
    }
   ],
   "source": [
    "from gymnasium import spaces\n",
    "\n",
    "no_of_stocks = 5\n",
    "stock_observation_shape = (no_of_stocks, 8)\n",
    "\n",
    "stock_lower_bounds = np.zeros(stock_observation_shape)\n",
    "stock_upper_bounds = np.full(stock_observation_shape, float('inf'))\n",
    "\n",
    "no_of_cmmdts = 6\n",
    "commodity_observation_shape = (no_of_cmmdts, 1) \n",
    "\n",
    "commodity_lower_bounds = np.zeros(commodity_observation_shape)\n",
    "commodity_upper_bounds = np.full(commodity_observation_shape, float('inf'))\n",
    "\n",
    "stock_observation_space = spaces.Box(low=stock_lower_bounds, high=stock_upper_bounds)\n",
    "commodity_observation_space = spaces.Box(low=commodity_lower_bounds, high=commodity_upper_bounds)\n",
    "\n",
    "wallet_observation_space = spaces.Box(low=0, high=float('inf'), shape=(1,))\n",
    "states = spaces.Tuple((stock_observation_space, commodity_observation_space, wallet_observation_space))\n",
    "\n",
    "print(states)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "v2env",
   "language": "python",
   "name": "v2env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
